/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    SvgIcon: (typeof import('./../src/components/SvgIcon/index.vue'))['default'];
    VanButton: (typeof import('vant/es'))['Button'];
    VanCell: (typeof import('vant/es'))['Cell'];
    VanCellGroup: (typeof import('vant/es'))['CellGroup'];
    VanConfigProvider: (typeof import('vant/es'))['ConfigProvider'];
    VanField: (typeof import('vant/es'))['Field'];
    VanNavBar: (typeof import('vant/es'))['NavBar'];
    VanPicker: (typeof import('vant/es'))['Picker'];
    VanPopup: (typeof import('vant/es'))['Popup'];
    VanSwitch: (typeof import('vant/es'))['Switch'];
    VanTabbar: (typeof import('vant/es'))['Tabbar'];
    VanTabbarItem: (typeof import('vant/es'))['TabbarItem'];
  }
}
