// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    VanCell: typeof import("vant/es")["Cell"];
    VanConfigProvider: typeof import("vant/es")["ConfigProvider"];
    VanSwitch: typeof import("vant/es")["Switch"];
    VanTabbar: typeof import("vant/es")["Tabbar"];
    VanTabbarItem: typeof import("vant/es")["TabbarItem"];
  }
}
